import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { headers } from "next/headers";
import "./globals.css";
import Providers from "./Providers";
import { FlexLayout } from "./components/flex-layout";
import { Header } from "./components/header/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const cookie = headers().get("cookie");

	return (
		<html lang="en">
			<body className={inter.className}>
				<Providers cookie={cookie}>
					<FlexLayout>{children}</FlexLayout>
				</Providers>
			</body>
		</html>
	);
}
