import type { Metadata } from "next";
import type React from "react";
// import { Inter } from "next/font/google";

import { headers } from "next/headers";
import "./globals.css";
import { MainProvider } from "./providers/main-provider";

import { FlexLayout } from "components";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const cookie = headers().get("cookie");

	return (
		<html lang="en">
			{/* <body className={inter.className}> */}
			<body>
				<MainProvider cookie={cookie}>
					<FlexLayout>{children}</FlexLayout>
				</MainProvider>
			</body>
		</html>
	);
}
